### ISSUE TITLE
notification color doesn't work

### ISSUE THREAD

**Issue by ktomaszx** [jdcargile/ms-teams-notification#62]
Hi,
do you have any idea why notification color doesn't work? I guess even default one 0b93ff is not displayed.
![image](https://github.com/jdcargile/ms-teams-notification/assets/99728548/10d72f47-bac2-4874-822e-aa7b9ddd10c0)

```
steps:
  - uses: actions/checkout@v4
  - name: Notify dedicated teams channel
    uses: jdcargile/ms-teams-notification@v1.4
    with:
      github-token: ${{ github.token }}
      ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      notification-summary: Test notification message 
      notification-color: ffc107
      verbose-logging: true
```
